# Generated by Django 2.1.1 on 2018-10-22 00:26

import discourz_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=discourz_app.models.user_directory_path),
        ),
    ]
