# Generated by Django 2.1.1 on 2018-10-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0002_auto_20181021_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=120),
            preserve_default=False,
        ),
    ]
