# Generated by Django 2.1.1 on 2018-10-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0003_account_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
    ]
