# Generated by Django 2.1.1 on 2018-10-23 03:59

import discourz_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0004_remove_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='account',
            name='img',
            field=models.ImageField(upload_to=discourz_app.models.user_directory_path),
        ),
    ]
