# Generated by Django 2.1.1 on 2018-12-05 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discourz_app', '0018_auto_20181202_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateMessage',
            fields=[
                ('text', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
