# Generated by Django 2.1.1 on 2018-12-05 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0019_debatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='debate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discourz_app.Debates'),
        ),
        migrations.AddField(
            model_name='debatemessage',
            name='debate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discourz_app.Debates'),
        ),
    ]
