# Generated by Django 2.1.1 on 2018-12-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0021_debates_other_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debates',
            name='position',
        ),
        migrations.RemoveField(
            model_name='pastdebates',
            name='user1Position',
        ),
        migrations.RemoveField(
            model_name='pastdebates',
            name='user2Position',
        ),
    ]
