# Generated by Django 2.1.1 on 2018-12-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0022_auto_20181206_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastdebates',
            name='firebaseKey',
            field=models.CharField(default='', max_length=500),
        ),
    ]
