# Generated by Django 2.1.1 on 2018-12-07 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0023_pastdebates_firebasekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='debate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discourz_app.PastDebates'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discourz_app.PollTopic'),
        ),
    ]
