# Generated by Django 2.1.1 on 2018-12-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0018_auto_20181202_1439'),
        ('discourz_app', '0024_auto_20181207_1326'),
    ]

    operations = [
    ]
