# Generated by Django 2.1.1 on 2018-12-08 19:05

import datetime
import discourz_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discourz_app', '0025_merge_20181207_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Discussion', primary_key=True, serialize=False)),
                ('isOpen', models.BooleanField(default=True)),
                ('tags', models.CharField(default='["General"]', max_length=100)),
                ('title', models.CharField(default='', max_length=500)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('img', models.ImageField(default='static/img/default.jpg', upload_to=discourz_app.models.discussion_directory_path)),
                ('initial_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
