# Generated by Django 2.1.1 on 2018-12-08 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0026_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='debates',
        ),
        migrations.AddField(
            model_name='chat',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discourz_app.Discussion'),
        ),
    ]
