# Generated by Django 2.1.1 on 2018-12-09 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0027_auto_20181208_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
