# Generated by Django 2.1.3 on 2018-12-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0029_auto_20181208_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='id',
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
    ]
